BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Answers ADD
	Accepted bit NULL
GO
ALTER TABLE dbo.Answers ADD CONSTRAINT
	DF_Answers_Accepted DEFAULT 0 FOR Accepted
GO
ALTER TABLE dbo.Answers SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
