/* UserLevel Defaults */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.UserLevel ADD CONSTRAINT
	DF_UserLevel_Level DEFAULT 0 FOR [Level]
GO
ALTER TABLE dbo.UserLevel ADD CONSTRAINT
	DF_UserLevel_Obtained DEFAULT SYSDATETIME() FOR Obtained
GO
ALTER TABLE dbo.UserLevel ADD CONSTRAINT
	DF_UserLevel_XP DEFAULT 0 FOR XP
GO
ALTER TABLE dbo.UserLevel SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* Questions Defaults*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Questions ADD CONSTRAINT
	DF_Questions_Added DEFAULT SYSDATETIME() FOR Added
GO
ALTER TABLE dbo.Questions ADD CONSTRAINT
	DF_Questions_Score DEFAULT 0 FOR Score
GO
ALTER TABLE dbo.Questions ADD CONSTRAINT
	DF_Questions_Bounty DEFAULT 0 FOR Bounty
GO
ALTER TABLE dbo.Questions SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* Comments Defaults*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Comments ADD CONSTRAINT
	DF_Comments_Added DEFAULT SYSDATETIME() FOR Added
GO
ALTER TABLE dbo.Comments ADD CONSTRAINT
	DF_Comments_Score DEFAULT 0 FOR Score
GO
ALTER TABLE dbo.Comments SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* Answers Defaults*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Answers ADD CONSTRAINT
	DF_Answers_Score DEFAULT 0 FOR Score
GO
ALTER TABLE dbo.Answers ADD CONSTRAINT
	DF_Answers_Added DEFAULT SYSDATETIME() FOR Added
GO
ALTER TABLE dbo.Answers SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* Users*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.AspNetUsers ADD CONSTRAINT
	DF_AspNetUsers_Credits DEFAULT 0 FOR Credits
GO
ALTER TABLE dbo.AspNetUsers SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* QuestionViews */
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE [dbo].[QuestionViews](
	[QuestionID] [uniqueidentifier] NOT NULL,
	[UserID] [nvarchar](128) NOT NULL,
	[Added] [datetime] NULL,
	[LastVisit] [datetime] NULL,
 CONSTRAINT [PK_QuestionViews] PRIMARY KEY CLUSTERED 
(
	[QuestionID] ASC,
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[QuestionViews] ADD  CONSTRAINT [DF_QuestionViews_SystemDate]  DEFAULT (SYSDATETIME()) FOR [Added]
GO
COMMIT

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.AspNetUsers SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Questions SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.QuestionViews ADD CONSTRAINT
	FK_QuestionViews_Questions FOREIGN KEY
	(
	QuestionID
	) REFERENCES dbo.Questions
	(
	ID
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.QuestionViews ADD CONSTRAINT
	FK_QuestionViews_AspNetUsers FOREIGN KEY
	(
	UserID
	) REFERENCES dbo.AspNetUsers
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.QuestionViews SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


GO

/****** Object:  Table [dbo].[ScoreItems] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ScoreItems](
	[ItemID] [uniqueidentifier] NOT NULL,
	[UserID] [nvarchar](128) NOT NULL,
	[Score] [decimal](18, 0) NULL,
	[Added] [datetime] NULL,
 CONSTRAINT [PK_ScoreItems] PRIMARY KEY CLUSTERED 
(
	[ItemID] ASC,
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ScoreItems] ADD  CONSTRAINT [DF_ScoreItems_Score]  DEFAULT ((0)) FOR [Score]
GO

ALTER TABLE [dbo].[ScoreItems] ADD  CONSTRAINT [DF_ScoreItems_Added]  DEFAULT (sysdatetime()) FOR [Added]
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.AspNetUsers SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ScoreItems ADD CONSTRAINT
	FK_ScoreItems_AspNetUsers FOREIGN KEY
	(
	UserID
	) REFERENCES dbo.AspNetUsers
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.ScoreItems SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
