/****** Object:  Table [dbo].[Gamification] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Gamification](
	[ID] [uniqueidentifier] NOT NULL,
	[Action] [nvarchar](256) NULL,
	[Points] [decimal](18, 0) NULL,
	[XP] [decimal](18, 0) NULL,
 CONSTRAINT [PK_Gamification] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Gamification ADD CONSTRAINT
	DF_Gamification_Points DEFAULT 0 FOR Points
GO
ALTER TABLE dbo.Gamification ADD CONSTRAINT
	DF_Gamification_XP DEFAULT 0 FOR XP
GO
ALTER TABLE dbo.Gamification SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Badges ADD
	Reward decimal(18, 0) NULL
GO
ALTER TABLE dbo.Badges ADD CONSTRAINT
	DF_Badges_Reward DEFAULT 0 FOR Reward
GO
ALTER TABLE dbo.Badges SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
